/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mice;

import java.util.*; //Import of the java util package


/**
 *
 * @author Victoria
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
            listHiredToCBRemove();
            //Fills in combo boxes with data.
            addProjectsToCBUpdate();
            addSpecialistToCBUpdate();
            hideHiredChangeFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tpMenu = new javax.swing.JTabbedPane();
        paneHired = new javax.swing.JPanel();
        lblErrorMessageHired = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        cbFunctions = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        tfsearchField = new javax.swing.JTextField();
        spHired = new javax.swing.JScrollPane();
        tasearchResult = new javax.swing.JTextArea();
        tpSubMenuHired = new javax.swing.JTabbedPane();
        paneChangeHired = new javax.swing.JPanel();
        btnChangeHired = new javax.swing.JButton();
        lblChangeMailHired = new javax.swing.JLabel();
        tfChangeMailHired = new javax.swing.JTextField();
        tfChangeTelephoneHired = new javax.swing.JTextField();
        lblChangeTelephoneHired = new javax.swing.JLabel();
        lblChangeNameHired = new javax.swing.JLabel();
        tfChangeNameHired = new javax.swing.JTextField();
        lblHeaderChangeHired = new javax.swing.JLabel();
        lblChooseHired = new javax.swing.JLabel();
        cbListAllHired = new javax.swing.JComboBox<>();
        btnChooseChangeHired = new javax.swing.JButton();
        paneRemoveHired = new javax.swing.JPanel();
        lblChooseHiredRemove = new javax.swing.JLabel();
        cbListAllHiredRemove = new javax.swing.JComboBox<>();
        btnRemove = new javax.swing.JButton();
        lblNote = new javax.swing.JLabel();
        lblHeaderRemove = new javax.swing.JLabel();
        paneAddHired = new javax.swing.JPanel();
        lblHeaderAdd = new javax.swing.JLabel();
        lblAddFirstName = new javax.swing.JLabel();
        tfAddFirstName = new javax.swing.JTextField();
        lblAddTelephone = new javax.swing.JLabel();
        tfAddTelephone = new javax.swing.JTextField();
        lblAddMail = new javax.swing.JLabel();
        tfAddMail = new javax.swing.JTextField();
        btnChangeHiredAdd = new javax.swing.JButton();
        lblAddLastName = new javax.swing.JLabel();
        tfAddLastName = new javax.swing.JTextField();
        paneUpdateHired = new javax.swing.JPanel();
        lblChooseGameProject = new javax.swing.JLabel();
        cbListAllGameProjects = new javax.swing.JComboBox<>();
        lblChooseProjectleader = new javax.swing.JLabel();
        cbListAllProjectleaders = new javax.swing.JComboBox<>();
        btnConfirmUpdate = new javax.swing.JButton();
        lblUpdateLeader = new javax.swing.JLabel();
        lblUpdateHiredInProject = new javax.swing.JLabel();
        lblUpdateHiredPosition = new javax.swing.JLabel();
        lblChooseSpecialist = new javax.swing.JLabel();
        cbListAllSpecialists = new javax.swing.JComboBox<>();
        lblChooseGameProjectUpdate = new javax.swing.JLabel();
        cbListAllGameProjectsUpdate = new javax.swing.JComboBox<>();
        btnConfirmUpdateHired = new javax.swing.JButton();
        lblChooseHiredPosition = new javax.swing.JLabel();
        cbListAllHiredPosition = new javax.swing.JComboBox<>();
        lblChooseUpgrade = new javax.swing.JLabel();
        cbHiredForm = new javax.swing.JComboBox<>();
        btnConfirmUpdatePosition = new javax.swing.JButton();
        btnConfirmUpdateRemoved = new javax.swing.JButton();
        separatorHired = new javax.swing.JSeparator();
        lblFunctionError = new javax.swing.JLabel();
        paneProject = new javax.swing.JPanel();
        lblHeaderGameProject = new javax.swing.JLabel();
        cbFunctionsGameProject = new javax.swing.JComboBox<>();
        tfsearchFieldGameProject = new javax.swing.JTextField();
        btnSearchGameProject = new javax.swing.JButton();
        spGameProject = new javax.swing.JScrollPane();
        tasearchResultGameProject = new javax.swing.JTextArea();
        lblErrorMessageGameProject = new javax.swing.JLabel();
        tpSubMenuGameProject = new javax.swing.JTabbedPane();
        paneAddGameProject = new javax.swing.JPanel();
        lblHeaderAddGameProject = new javax.swing.JLabel();
        lblInfoTextAddGameProject = new javax.swing.JLabel();
        spGameProjectAdd = new javax.swing.JScrollPane();
        tpReturnNewSID = new javax.swing.JTextPane();
        btnGenerateSID = new javax.swing.JButton();
        lblGpAddName = new javax.swing.JLabel();
        tfGpAddName = new javax.swing.JTextField();
        lblGpAddStartDate = new javax.swing.JLabel();
        tfAddGpStartDate = new javax.swing.JTextField();
        tfAddGpReleaseDate = new javax.swing.JTextField();
        lblGpAddReleaseDate = new javax.swing.JLabel();
        btnAddGameProject = new javax.swing.JButton();
        paneChangeGameProject = new javax.swing.JPanel();
        lblHeaderChangeGameProject = new javax.swing.JLabel();
        lblChooseGame = new javax.swing.JLabel();
        cbListAllGames = new javax.swing.JComboBox<>();
        btnChooseChangeGameProject = new javax.swing.JButton();
        btnChangeGameProject = new javax.swing.JButton();
        tfChangeGpReleaseDate = new javax.swing.JTextField();
        lblGpChangeReleaseDate = new javax.swing.JLabel();
        lblGpChangeStartDate = new javax.swing.JLabel();
        tfChangeGpStartDate = new javax.swing.JTextField();
        tfGpChangeName = new javax.swing.JTextField();
        lblGpChangeName = new javax.swing.JLabel();
        separatorGameProject = new javax.swing.JSeparator();
        panePlatform = new javax.swing.JPanel();
        spPlatform = new javax.swing.JScrollPane();
        tasearchResultPlatform = new javax.swing.JTextArea();
        btnSearchPlatform = new javax.swing.JButton();
        tfsearchFieldPlatform = new javax.swing.JTextField();
        cbFunctionsPlatform = new javax.swing.JComboBox<>();
        lblHeaderPlatform = new javax.swing.JLabel();
        lblErrorMessagePlatform = new javax.swing.JLabel();
        paneCompetence = new javax.swing.JPanel();
        spCompetence = new javax.swing.JScrollPane();
        tasearchResultCompetence = new javax.swing.JTextArea();
        btnSearchCompetence = new javax.swing.JButton();
        tfsearchFieldCompetence = new javax.swing.JTextField();
        cbFunctionsCompetence = new javax.swing.JComboBox<>();
        lblHeaderCompetence = new javax.swing.JLabel();
        lblErrorMessageCompetence = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setText("Välj funktion:");

        cbFunctions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sök anställd i ett projekt (A,S)", "Sök anställd som leder projekt (A,S)", "Ändra information om en anställd (A)", "Ta bort anställd (A)", "Lägg till ny anställd (A)", "Uppdatera anställd (A)", " ", " " }));

        btnSearch.setText("Sök");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tfsearchField.setText("Sök...");

        tasearchResult.setColumns(20);
        tasearchResult.setRows(5);
        spHired.setViewportView(tasearchResult);

        btnChangeHired.setText("OK");
        btnChangeHired.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeHiredMouseClicked(evt);
            }
        });

        lblChangeMailHired.setText("Mail:");

        tfChangeMailHired.setText("Mailadress");

        tfChangeTelephoneHired.setText("Telefonnummer");

        lblChangeTelephoneHired.setText("Telefon: ");

        lblChangeNameHired.setText("Namn:");

        tfChangeNameHired.setText("Namn");

        lblHeaderChangeHired.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeaderChangeHired.setText("Ändra anställd");

        lblChooseHired.setText("Välj en anställd i listan att ändra information om: ");

        btnChooseChangeHired.setText("Välj");
        btnChooseChangeHired.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseChangeHiredMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneChangeHiredLayout = new javax.swing.GroupLayout(paneChangeHired);
        paneChangeHired.setLayout(paneChangeHiredLayout);
        paneChangeHiredLayout.setHorizontalGroup(
            paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChangeHiredLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneChangeHiredLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChooseHired)
                            .addGroup(paneChangeHiredLayout.createSequentialGroup()
                                .addComponent(cbListAllHired, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChooseChangeHired)))
                        .addGap(110, 110, 110)
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChangeNameHired)
                            .addComponent(lblChangeMailHired)
                            .addComponent(lblChangeTelephoneHired))
                        .addGap(34, 34, 34)
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfChangeTelephoneHired)
                            .addComponent(tfChangeNameHired)
                            .addComponent(tfChangeMailHired, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneChangeHiredLayout.createSequentialGroup()
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHeaderChangeHired, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChangeHired, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(83, 83, 83))
        );
        paneChangeHiredLayout.setVerticalGroup(
            paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChangeHiredLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeaderChangeHired, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneChangeHiredLayout.createSequentialGroup()
                        .addComponent(lblChooseHired)
                        .addGap(11, 11, 11)
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbListAllHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChooseChangeHired))
                        .addGap(55, 55, 55)
                        .addComponent(btnChangeHired))
                    .addGroup(paneChangeHiredLayout.createSequentialGroup()
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfChangeNameHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChangeNameHired))
                        .addGap(8, 8, 8)
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChangeTelephoneHired)
                            .addComponent(tfChangeTelephoneHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneChangeHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChangeMailHired)
                            .addComponent(tfChangeMailHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tpSubMenuHired.addTab("Ändra", paneChangeHired);

        lblChooseHiredRemove.setText("Välj anställd i listan att ta bort ur systemet:");

        btnRemove.setText("Ta bort");
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });

        lblNote.setText("OBSERVERA! Du kan ej ändra dig när du har tagit bort en anställd");

        lblHeaderRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeaderRemove.setText("Ta bort anställd");

        javax.swing.GroupLayout paneRemoveHiredLayout = new javax.swing.GroupLayout(paneRemoveHired);
        paneRemoveHired.setLayout(paneRemoveHiredLayout);
        paneRemoveHiredLayout.setHorizontalGroup(
            paneRemoveHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoveHiredLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(paneRemoveHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaderRemove)
                    .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneRemoveHiredLayout.createSequentialGroup()
                        .addGroup(paneRemoveHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChooseHiredRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbListAllHiredRemove, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnRemove)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        paneRemoveHiredLayout.setVerticalGroup(
            paneRemoveHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRemoveHiredLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeaderRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChooseHiredRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneRemoveHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbListAllHiredRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNote)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        tpSubMenuHired.addTab("Ta bort", paneRemoveHired);

        lblHeaderAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeaderAdd.setText("Lägg till anställd");

        lblAddFirstName.setText("Förnamn:");

        tfAddFirstName.setText("Förnamn");

        lblAddTelephone.setText("Telefon: ");

        tfAddTelephone.setText("Telefonnummer");

        lblAddMail.setText("Mail:");

        tfAddMail.setText("Mailadress");

        btnChangeHiredAdd.setText("OK");
        btnChangeHiredAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeHiredAddMouseClicked(evt);
            }
        });

        lblAddLastName.setText("Efternamn:");

        tfAddLastName.setText("Efternamn");

        javax.swing.GroupLayout paneAddHiredLayout = new javax.swing.GroupLayout(paneAddHired);
        paneAddHired.setLayout(paneAddHiredLayout);
        paneAddHiredLayout.setHorizontalGroup(
            paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddHiredLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHeaderAdd)
                    .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnChangeHiredAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAddHiredLayout.createSequentialGroup()
                            .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(paneAddHiredLayout.createSequentialGroup()
                                    .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAddMail)
                                        .addComponent(lblAddTelephone))
                                    .addGap(33, 33, 33))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneAddHiredLayout.createSequentialGroup()
                                    .addComponent(lblAddFirstName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfAddTelephone)
                                .addComponent(tfAddFirstName)
                                .addComponent(tfAddMail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAddHiredLayout.createSequentialGroup()
                        .addComponent(lblAddLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        paneAddHiredLayout.setVerticalGroup(
            paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddHiredLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHeaderAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddFirstName))
                .addGap(4, 4, 4)
                .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddTelephone)
                    .addComponent(tfAddTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneAddHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddMail)
                    .addComponent(tfAddMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeHiredAdd)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tpSubMenuHired.addTab("Lägg till", paneAddHired);

        lblChooseGameProject.setText("Välj Spelprojekt: ");

        lblChooseProjectleader.setText("Välj projektledare: ");

        btnConfirmUpdate.setText("OK");
        btnConfirmUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmUpdateMouseClicked(evt);
            }
        });

        lblUpdateLeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpdateLeader.setText("Uppdatera information om vem som leder ett projekt");

        lblUpdateHiredInProject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpdateHiredInProject.setText("Uppdatera information om vilka anställda som arbetar med ett spelprojekt");

        lblUpdateHiredPosition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUpdateHiredPosition.setText("Uppdatera den anställdes roll (A)");

        lblChooseSpecialist.setText("Välj Specialist: ");

        lblChooseGameProjectUpdate.setText("Välj Spelprojekt: ");

        btnConfirmUpdateHired.setText("Lägg till");
        btnConfirmUpdateHired.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmUpdateHiredMouseClicked(evt);
            }
        });

        lblChooseHiredPosition.setText("Välj Anställd: ");

        lblChooseUpgrade.setText("Välj ändring i anställning:");

        btnConfirmUpdatePosition.setText("OK");

        btnConfirmUpdateRemoved.setText("Ta bort");
        btnConfirmUpdateRemoved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmUpdateRemovedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneUpdateHiredLayout = new javax.swing.GroupLayout(paneUpdateHired);
        paneUpdateHired.setLayout(paneUpdateHiredLayout);
        paneUpdateHiredLayout.setHorizontalGroup(
            paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateHiredLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneUpdateHiredLayout.createSequentialGroup()
                        .addGroup(paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneUpdateHiredLayout.createSequentialGroup()
                                .addComponent(lblChooseHiredPosition)
                                .addGap(18, 18, 18)
                                .addComponent(cbListAllHiredPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblChooseUpgrade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbHiredForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmUpdatePosition))
                            .addComponent(lblUpdateHiredPosition)
                            .addComponent(lblUpdateHiredInProject)
                            .addComponent(lblUpdateLeader)
                            .addGroup(paneUpdateHiredLayout.createSequentialGroup()
                                .addComponent(lblChooseGameProject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbListAllGameProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblChooseProjectleader)
                                .addGap(18, 18, 18)
                                .addComponent(cbListAllProjectleaders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmUpdate)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneUpdateHiredLayout.createSequentialGroup()
                        .addComponent(lblChooseSpecialist)
                        .addGap(18, 18, 18)
                        .addComponent(cbListAllSpecialists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblChooseGameProjectUpdate)
                        .addGap(26, 26, 26)
                        .addComponent(cbListAllGameProjectsUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmUpdateRemoved)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmUpdateHired)
                        .addGap(56, 56, 56))))
        );
        paneUpdateHiredLayout.setVerticalGroup(
            paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateHiredLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblUpdateLeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseGameProject)
                    .addComponent(cbListAllGameProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChooseProjectleader)
                    .addComponent(cbListAllProjectleaders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUpdateHiredInProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseSpecialist)
                    .addComponent(cbListAllSpecialists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChooseGameProjectUpdate)
                    .addComponent(cbListAllGameProjectsUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmUpdateHired)
                    .addComponent(btnConfirmUpdateRemoved))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUpdateHiredPosition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneUpdateHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseHiredPosition)
                    .addComponent(cbListAllHiredPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChooseUpgrade)
                    .addComponent(cbHiredForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmUpdatePosition))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tpSubMenuHired.addTab("Uppdatera", paneUpdateHired);

        lblFunctionError.setText(" ");

        javax.swing.GroupLayout paneHiredLayout = new javax.swing.GroupLayout(paneHired);
        paneHired.setLayout(paneHiredLayout);
        paneHiredLayout.setHorizontalGroup(
            paneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHiredLayout.createSequentialGroup()
                .addGroup(paneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneHiredLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(paneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spHired, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneHiredLayout.createSequentialGroup()
                                .addComponent(lblHeader)
                                .addGap(4, 4, 4)
                                .addComponent(cbFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfsearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch)
                                .addGap(18, 18, 18)
                                .addComponent(lblErrorMessageHired, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFunctionError))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneHiredLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separatorHired))
                    .addGroup(paneHiredLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tpSubMenuHired)))
                .addContainerGap())
        );
        paneHiredLayout.setVerticalGroup(
            paneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHiredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpSubMenuHired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorHired, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneHiredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeader)
                        .addComponent(cbFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(tfsearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorMessageHired, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spHired, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFunctionError)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tpMenu.addTab("Anställd", paneHired);

        lblHeaderGameProject.setText("Välj funktion:");

        cbFunctionsGameProject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa vem som leder/har lett ett specifikt projekt (sök Spel) (A,S)", "Visa vilka plattformar ett spel utvecklas till (A,S)", "Lista de spelprojekt som är under utveckling (A,S)", "Lista de spelprojekt som har släppts (A,S)", "Lägg till spelutvecklingsprojekt (A)", "Uppdatera information om ett specifikt projekt (Sök Spel) (A)", " ", " " }));

        tfsearchFieldGameProject.setText("Sök...");

        btnSearchGameProject.setText("Sök");

        tasearchResultGameProject.setColumns(20);
        tasearchResultGameProject.setRows(5);
        spGameProject.setViewportView(tasearchResultGameProject);

        lblHeaderAddGameProject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeaderAddGameProject.setText("Lägg till ett nytt projekt!");

        lblInfoTextAddGameProject.setText("Generera ett nytt spelprojektsID:");

        spGameProjectAdd.setViewportView(tpReturnNewSID);

        btnGenerateSID.setText("Generera");

        lblGpAddName.setText("Beteckning:");

        tfGpAddName.setText("Namn");

        lblGpAddStartDate.setText("Startdatum:");

        tfAddGpStartDate.setText("ÅÅÅÅ.MM.DD");

        tfAddGpReleaseDate.setText("ÅÅÅÅ.MM.DD");

        lblGpAddReleaseDate.setText("Releasedatum:");

        btnAddGameProject.setText("OK");

        javax.swing.GroupLayout paneAddGameProjectLayout = new javax.swing.GroupLayout(paneAddGameProject);
        paneAddGameProject.setLayout(paneAddGameProjectLayout);
        paneAddGameProjectLayout.setHorizontalGroup(
            paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddGameProjectLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAddGameProjectLayout.createSequentialGroup()
                        .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerateSID)
                            .addComponent(lblInfoTextAddGameProject)
                            .addComponent(lblHeaderAddGameProject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGpAddName)
                            .addComponent(lblGpAddReleaseDate)
                            .addComponent(lblGpAddStartDate))
                        .addGap(26, 26, 26)
                        .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfAddGpStartDate)
                            .addComponent(tfGpAddName)
                            .addComponent(tfAddGpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneAddGameProjectLayout.createSequentialGroup()
                        .addComponent(spGameProjectAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddGameProject)))
                .addGap(68, 68, 68))
        );
        paneAddGameProjectLayout.setVerticalGroup(
            paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddGameProjectLayout.createSequentialGroup()
                .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAddGameProjectLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblHeaderAddGameProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInfoTextAddGameProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerateSID)
                        .addGap(13, 13, 13)
                        .addComponent(spGameProjectAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneAddGameProjectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGpAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGpAddName))
                        .addGap(8, 8, 8)
                        .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGpAddStartDate)
                            .addComponent(tfAddGpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneAddGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGpAddReleaseDate)
                            .addComponent(tfAddGpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddGameProject)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tpSubMenuGameProject.addTab("Lägg till", paneAddGameProject);

        lblHeaderChangeGameProject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeaderChangeGameProject.setText("Ändra spelprojekt");

        lblChooseGame.setText("Välj ett spel i listan att ändra information om: ");

        btnChooseChangeGameProject.setText("Välj");

        btnChangeGameProject.setText("OK");

        tfChangeGpReleaseDate.setText("ÅÅÅÅ.MM.DD");

        lblGpChangeReleaseDate.setText("Releasedatum:");

        lblGpChangeStartDate.setText("Startdatum:");

        tfChangeGpStartDate.setText("ÅÅÅÅ.MM.DD");

        tfGpChangeName.setText("Namn");

        lblGpChangeName.setText("Beteckning:");

        javax.swing.GroupLayout paneChangeGameProjectLayout = new javax.swing.GroupLayout(paneChangeGameProject);
        paneChangeGameProject.setLayout(paneChangeGameProjectLayout);
        paneChangeGameProjectLayout.setHorizontalGroup(
            paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                        .addComponent(lblHeaderChangeGameProject)
                        .addGap(0, 499, Short.MAX_VALUE))
                    .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblChooseGame)
                            .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                                .addComponent(cbListAllGames, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChooseChangeGameProject)))
                        .addGap(125, 125, 125)
                        .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                                .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGpChangeName)
                                    .addComponent(lblGpChangeReleaseDate)
                                    .addComponent(lblGpChangeStartDate))
                                .addGap(26, 26, 26)
                                .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfChangeGpStartDate)
                                    .addComponent(tfGpChangeName)
                                    .addComponent(tfChangeGpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(btnChangeGameProject)))
                        .addGap(47, 47, 47))))
        );
        paneChangeGameProjectLayout.setVerticalGroup(
            paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHeaderChangeGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                        .addComponent(lblChooseGame)
                        .addGap(11, 11, 11)
                        .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbListAllGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChooseChangeGameProject)))
                    .addGroup(paneChangeGameProjectLayout.createSequentialGroup()
                        .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfGpChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGpChangeName))
                        .addGap(8, 8, 8)
                        .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGpChangeStartDate)
                            .addComponent(tfChangeGpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneChangeGameProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGpChangeReleaseDate)
                            .addComponent(tfChangeGpReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnChangeGameProject)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tpSubMenuGameProject.addTab("Ändra", paneChangeGameProject);

        javax.swing.GroupLayout paneProjectLayout = new javax.swing.GroupLayout(paneProject);
        paneProject.setLayout(paneProjectLayout);
        paneProjectLayout.setHorizontalGroup(
            paneProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpSubMenuGameProject)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProjectLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneProjectLayout.createSequentialGroup()
                        .addComponent(lblHeaderGameProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFunctionsGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfsearchFieldGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchGameProject))
                    .addComponent(spGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessageGameProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(paneProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separatorGameProject)
                .addContainerGap())
        );
        paneProjectLayout.setVerticalGroup(
            paneProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpSubMenuGameProject)
                .addGap(10, 10, 10)
                .addComponent(separatorGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeaderGameProject)
                        .addComponent(cbFunctionsGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfsearchFieldGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchGameProject))
                    .addComponent(lblErrorMessageGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spGameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        tpMenu.addTab("Spelprojekt", paneProject);

        tasearchResultPlatform.setColumns(20);
        tasearchResultPlatform.setRows(5);
        spPlatform.setViewportView(tasearchResultPlatform);

        btnSearchPlatform.setText("Sök");

        tfsearchFieldPlatform.setText("Sök...");

        cbFunctionsPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de spel som har släppts till plattformen (A,S)", "Uppdatera information om vilka plattformar ett spelprojekt omfattar (A)" }));

        lblHeaderPlatform.setText("Välj funktion:");

        javax.swing.GroupLayout panePlatformLayout = new javax.swing.GroupLayout(panePlatform);
        panePlatform.setLayout(panePlatformLayout);
        panePlatformLayout.setHorizontalGroup(
            panePlatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePlatformLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panePlatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spPlatform)
                    .addGroup(panePlatformLayout.createSequentialGroup()
                        .addComponent(lblHeaderPlatform)
                        .addGap(18, 18, 18)
                        .addComponent(cbFunctionsPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tfsearchFieldPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchPlatform)))
                .addGap(18, 18, 18)
                .addComponent(lblErrorMessagePlatform, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        panePlatformLayout.setVerticalGroup(
            panePlatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePlatformLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panePlatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panePlatformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeaderPlatform)
                        .addComponent(cbFunctionsPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfsearchFieldPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchPlatform))
                    .addComponent(lblErrorMessagePlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        tpMenu.addTab("Plattform", panePlatform);

        tasearchResultCompetence.setColumns(20);
        tasearchResultCompetence.setRows(5);
        spCompetence.setViewportView(tasearchResultCompetence);

        btnSearchCompetence.setText("Sök");

        tfsearchFieldCompetence.setText("Sök...");

        cbFunctionsCompetence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista den kompetens en specifik specialist har (Sök anställd) (A,S)", "Uppdatera information om vilka domäner en specialist har kompetens för (A)", " " }));

        lblHeaderCompetence.setText("Välj funktion:");

        javax.swing.GroupLayout paneCompetenceLayout = new javax.swing.GroupLayout(paneCompetence);
        paneCompetence.setLayout(paneCompetenceLayout);
        paneCompetenceLayout.setHorizontalGroup(
            paneCompetenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCompetenceLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(paneCompetenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spCompetence)
                    .addGroup(paneCompetenceLayout.createSequentialGroup()
                        .addComponent(lblHeaderCompetence)
                        .addGap(18, 18, 18)
                        .addComponent(cbFunctionsCompetence, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tfsearchFieldCompetence, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchCompetence)))
                .addGap(31, 31, 31)
                .addComponent(lblErrorMessageCompetence, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        paneCompetenceLayout.setVerticalGroup(
            paneCompetenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCompetenceLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneCompetenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneCompetenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHeaderCompetence)
                        .addComponent(cbFunctionsCompetence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfsearchFieldCompetence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchCompetence))
                    .addComponent(lblErrorMessageCompetence, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCompetence, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        tpMenu.addTab("Kompetensdomän", paneCompetence);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * A method for looking through and choosing which method too use in the combobox
     * @param evt 
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String selectedFunction = cbFunctions.getSelectedItem().toString();
               //valid.containsString(tfsearchField.getText())
        switch (selectedFunction)
        {
            case "Sök anställd i ett projekt (A,S)" :
                listHired();
                hideHiredChangeFields();
                break;
            case "Sök anställd som leder projekt (A,S)":
                listProjects();
                hideHiredChangeFields();
                break;  
            case "Ändra information om en anställd (A)":
                showHiredChangeFields();
                updateCBs();
                break;
            case "Ta bort anställd (A)" :
                showHiredRemoveFields();
                break;
            case "Lägg till ny anställd (A)" :
                showHiredAddFields();
                break;
            case "Uppdatera anställd (A)" : 
                showHiredUpdateFields();
                updateCBs();
                break;       
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
    *Adds all leaders to a combobox
    */
    public void addProjectleadersToCB()
    {
	DbClass database = new DbClass();
	
	ArrayList<HashMap<String, String>> allLeaders = database.listAllLeaders();
	for (int i = 0; i < allLeaders.size(); i++)
	{
		String aid = allLeaders.get(i).get("AID");
		String name = allLeaders.get(i).get("NAMN");
		cbListAllProjectleaders.addItem(aid + ", " + name);
	}
    }
    
    /**
     * Event on mouseclick that sets the choosen one that you want to update information about
     * @param evt 
     */
    private void btnChooseChangeHiredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseChangeHiredMouseClicked
        String currentHired = cbListAllHired.getSelectedItem().toString();
        int aid = Integer.parseInt(currentHired.split(",")[0]);
        
        DbClass database = new DbClass();
        
        //populate textfields with existing data
        HashMap<String, String> hired = database.listHired(aid);
        String name = hired.get("NAMN");
        tfChangeNameHired.setText(name);
        String phone = hired.get("TELEFON");
        tfChangeTelephoneHired.setText(phone);
        String mail = hired.get("MAIL");
        tfChangeMailHired.setText(mail);
        
    }//GEN-LAST:event_btnChooseChangeHiredMouseClicked

    /**
     * Event on mouse click that lets you set the new information about a hired one. 
     * @param evt 
     */
    private void btnChangeHiredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeHiredMouseClicked
        String currentHired = cbListAllHired.getSelectedItem().toString();      //Det här med kod-duplicering.. Kolla "btnChooseChangeMouseClicked metoden...
                int aid = Integer.parseInt(currentHired.split(",")[0]);
        changeInfoAboutHired(aid);
    }//GEN-LAST:event_btnChangeHiredMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        String currentHired = cbListAllHiredRemove.getSelectedItem().toString();
        String deleteAID = (currentHired.split(",")[0]);
        removeHired(deleteAID);
        updateCBs();
    }//GEN-LAST:event_btnRemoveMouseClicked

    /**
     * lets u delete a hired person
     * @param deleteAID 
     */
    private void removeHired (String deleteAID)
    {
      //Remove the person selected in the combobox.
      DbClass database = new DbClass();
                
        database.deleteHired(deleteAID);
    }          
    
    private void listHiredToCBRemove()
    {
   DbClass database = new DbClass();
        //Fetches the names of all of the staff, and holds all info in a cb.
        ArrayList<HashMap<String, String>> allHired = database.listAllHired();
        for (int i = 0; i < allHired.size(); i++)
        {
            String aid = allHired.get(i).get("AID");
            String name = allHired.get(i).get("NAMN");
            cbListAllHiredRemove.addItem(aid + ", " + name);
        }
    }
    
    public void updateCBs ()
    {
        cbListAllHiredRemove.removeAllItems();
        listHiredToCBRemove();
        cbListAllProjectleaders.removeAllItems();
        addProjectleadersToCB();
        cbListAllGameProjects.removeAllItems();
        addProjectsToCB();
        cbListAllHired.removeAllItems();
        addHiredToCB();
    }
    
    
    private void btnConfirmUpdateHiredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmUpdateHiredMouseClicked
        // Update a specialist to show a new project said specialist is working on.  
        DbClass database = new DbClass();
        
        String specialist = cbListAllSpecialists.getSelectedItem().toString();
        String project = cbListAllGameProjectsUpdate.getSelectedItem().toString();
        database.updateSpecialistProject(specialist, project);
        
    }//GEN-LAST:event_btnConfirmUpdateHiredMouseClicked

    private void btnConfirmUpdateRemovedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmUpdateRemovedMouseClicked
        // Update a specialist to show a project that the specialist is no longer
        //working on.
        DbClass database = new DbClass();
         
        String specialist = cbListAllSpecialists.getSelectedItem().toString();
        String project = cbListAllGameProjectsUpdate.getSelectedItem().toString();
        database.deleteSpecialistProject(specialist, project);
        
    }//GEN-LAST:event_btnConfirmUpdateRemovedMouseClicked

    private void btnChangeHiredAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeHiredAddMouseClicked
        //add a hired person
        addNewHired();
        updateCBs();
    }//GEN-LAST:event_btnChangeHiredAddMouseClicked

    private void btnConfirmUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmUpdateMouseClicked
        /**String currentLeader = cbListAllProjectleaders.getSelectedItem().toString();
	String currentGame = cbListAllGameProjects.getSelectedItem().toString();
	int aid = Integer.parseInt(currentLeader.split(",")[0]);
	String game = currentGame.split(",")[1];*/
	updateHired();
    }//GEN-LAST:event_btnConfirmUpdateMouseClicked

    /**
* calls the database updateHired-methos and sends the new info to it.
*/
public void updateHired()           //FRÅGA JOHANNNNNNNNNN
{
	DbClass database = new DbClass();
	String currentLeader = cbListAllProjectleaders.getSelectedItem().toString();
	String currentGame = cbListAllGameProjects.getSelectedItem().toString();
	int aid = Integer.parseInt(currentLeader.split(",")[0]);
	String game = currentGame.split(",")[1];
        //String theLeaders = cbListAllProjectleaders.getSelectedItem().toString();
        boolean match = false;
        
	HashMap<String, String> thisLeader = database.listALeader(aid);
	for (String leader: thisLeader.keySet())
        {
            if (!currentLeader.equals(leader))
            {
                match = true;
            }
        }
        
        if(match)
            {
		database.updateHired(aid, game);
		System.out.println("Uppdateringen utförd");
            }
            else
            {
		System.out.println("Ett felmeddelande här");
            }
}
    
    public void addProjectsToCBUpdate()			
{       //Adds all the projects a specialist can work on to a cb.
	DbClass database = new DbClass();
	
	ArrayList<HashMap<String, String>> allProjects = database.listAllProjects();
	for (int i = 0; i < allProjects.size(); i++)
	{
		String sid = allProjects.get(i).get("SID");
		String beteckning = allProjects.get(i).get("BETECKNING");
		cbListAllGameProjectsUpdate.addItem(sid + "," + beteckning);
	}
}
    
        public void addProjectsToCB()			
{       //Adds all the projects a specialist can work on to a cb.
	DbClass database = new DbClass();
	
	ArrayList<HashMap<String, String>> allProjects = database.listAllProjects();
	for (int i = 0; i < allProjects.size(); i++)
	{
		String sid = allProjects.get(i).get("SID");
		String beteckning = allProjects.get(i).get("BETECKNING");
		cbListAllGameProjects.addItem(sid + ", " + beteckning);
	}
}

public void addSpecialistToCBUpdate()			
{       //Adds all the projects a specialist can work on to a cb.
	DbClass database = new DbClass();
	
	ArrayList<HashMap<String, String>> allProjects = database.listAllSpecialists();
	for (int i = 0; i < allProjects.size(); i++)
	{
		//String sid = allProjects.get(i).get("SID");
		String namn = allProjects.get(i).get("NAMN");
		cbListAllSpecialists.addItem(namn);
	}
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }  
    
    /**
     * Lists the projects a person is working on.
     */
    private void listHired ()
    {
        String searchWord = tfsearchField.getText();
        DbClass database = new DbClass();
        tasearchResult.setText("");
        boolean validation = Validation.containsString(searchWord);
        if (Validation.textBoxTextIsRequired(tfsearchField) && validation)
        {
            lblErrorMessageHired.setText("");
            ArrayList<String> listHired = database.listHiredInProject(searchWord);
            for(String beteckning: listHired)
            {
                tasearchResult.append(beteckning + "\n");
            }
        }
        else
        {
            lblErrorMessageHired.setText("Använd endast a-ö, A-Ö");
        }
    }
    
    /**
     * Lists the projects a person os leading
     */
    private void listProjects ()
    {
         String searchWord = tfsearchField.getText();
         DbClass database = new DbClass();
         tasearchResult.setText("");
         boolean validation = Validation.containsString(searchWord);
        if (Validation.textBoxTextIsRequired(tfsearchField) && validation)
        {
            lblErrorMessageHired.setText("");
            
            ArrayList<HashMap<String, String>> listProject = database.listProjects(searchWord);
            if (listProject != null)
            {
                for(int i = 0; i < listProject.size(); i++)
                {
                    String beteckningen = listProject.get(i).get("BETECKNING");
                    String startdatumet = listProject.get(i).get("STARTDATUM");
                    String releasedatumet = listProject.get(i).get("RELEASEDATUM");
                    tasearchResult.append(beteckningen + " " + startdatumet + " " + releasedatumet + "\n");
                }
            }
            else
            {
                lblFunctionError.setText("Personen arbetar inte med några projekt");
                
            }
        }
        else
        {
            lblErrorMessageHired.setText("Använd endast a-ö, A-Ö");
        }
    }
    
    /**
     * A method that generates all the hired staff in a combobox-list.
     */
    private void addHiredToCB()
    {
        DbClass database = new DbClass();
        //create a cb that holds all the hired staff
        ArrayList<HashMap<String, String>> allHired = database.listAllHired();
        for (int i = 0; i < allHired.size(); i++)
        {
            String aid = allHired.get(i).get("AID");
            String name = allHired.get(i).get("NAMN");
            cbListAllHired.addItem(aid + ", " + name);
        }
    }
    
    /**
     * Lets you change information about the choosen one(Harry Potter-reference).
     * @param AID 
     */
    private void changeInfoAboutHired (int AID)
    {
        DbClass database = new DbClass();
        HashMap<String, String> hired = database.listHired(AID);
        
        
        //Gets the current name from the database
        String existingName = hired.get("NAMN");
        String setName = tfChangeNameHired.getText();
        String existingTelephone = hired.get("TELEFON");
        String setPhone = tfChangeTelephoneHired.getText();
        String existingMail = hired.get("MAIL");
        String setMail = tfChangeMailHired.getText();
        if (!setName.equals(existingName) || !setPhone.equals(existingTelephone) || !setMail.equals(existingMail))
        {
            database.changeHired(setName, setPhone, setMail, AID);
            System.out.println("Ändring genomförd");
        }
        else
        {
            System.out.println("nope");
        }
    }
    
    /**
* Throws the new info about a hired to the database-class
*/
public void addNewHired ()
{
	DbClass database = new DbClass();
	
        int newAID = database.generateAID();
        String firstname = tfAddFirstName.getText();
        String lastname = tfAddLastName.getText();
	
        //Gets the info from the textboxes
        if (Validation.containsString(firstname) && Validation.containsString(lastname) && Validation.checkName(firstname, lastname))
        {
            firstname =  tfAddFirstName.getText(); 
            lastname = tfAddLastName.getText();
        }
        String phone = tfAddTelephone.getText();
        String mail = tfAddMail.getText();
				
		//Create a username based on the firstnames first letter, the lastnames first and last letter.
		String sistaBokstaven = lastname.substring(lastname.length()-1, lastname.length());
		String username = firstname.substring(0,1) + lastname.substring(0,1) + sistaBokstaven;
                
		
		//checks if there is any text in the textfields and then adds the text in them to the database
        if (Validation.textBoxTextIsRequired(tfAddFirstName) && Validation.textBoxTextIsRequired(tfAddLastName) && Validation.textBoxTextIsRequired(tfAddTelephone) && Validation.textBoxTextIsRequired(tfAddMail))
        {
            String name = firstname + " " + lastname;
            database.addHired(newAID, name, phone, mail, username);
            System.out.println(name + " är nu tillagd!");
        }
        else
        {
            System.out.println("nope");
        }
    }
  
    /**
     * Shows the fields about a Hired when someone with full access is logged in
     */
    private void showHiredChangeFields()
    {
        paneChangeHired.setVisible(true);
	tpSubMenuHired.setVisible(true);
	lblHeaderChangeHired.setVisible(true);
	lblChooseHired.setVisible(true);
	cbListAllHired.setVisible(true);
	btnChooseChangeHired.setVisible(true);
	lblChangeNameHired.setVisible(true);
	tfChangeNameHired.setVisible(true);
	lblChangeTelephoneHired.setVisible(true);
	tfChangeTelephoneHired.setVisible(true);
	lblChangeMailHired.setVisible(true);
	tfChangeMailHired.setVisible(true);
	btnChangeHired.setVisible(true);
    }
    
    /**
     * Hides the fields about a Hired when someone without full access is using the program
     */
    private void hideHiredChangeFields()
    {     
        paneChangeHired.setVisible(false);
	tpSubMenuHired.setVisible(false);
	lblHeaderChangeHired.setVisible(false);
	lblChooseHired.setVisible(false);
	cbListAllHired.setVisible(false);
	btnChooseChangeHired.setVisible(false);
	lblChangeNameHired.setVisible(false);
	tfChangeNameHired.setVisible(false);
	lblChangeTelephoneHired.setVisible(false);
	tfChangeTelephoneHired.setVisible(false);
	lblChangeMailHired.setVisible(false);
	tfChangeMailHired.setVisible(false);
	btnChangeHired.setVisible(false);
    }
    
    /**
     * Shows the fields for removing a Hired when someone with full access is using the program
     */
    private void showHiredRemoveFields ()
    {
	tpSubMenuHired.setVisible(true);
	paneRemoveHired.setVisible(true);
	lblChooseHiredRemove.setVisible(true);
	cbListAllHiredRemove.setVisible(true);
	btnRemove.setVisible(true);
	lblNote.setVisible(true);
	lblHeaderRemove.setVisible(true);
    }

    /**
     * Hides the fields for removing a Hired when someone without full access is using the program
     */
    private void hideHiredRemoveFields ()
    {
	tpSubMenuHired.setVisible(false);
	paneRemoveHired.setVisible(false);
	lblChooseHiredRemove.setVisible(false);
	cbListAllHiredRemove.setVisible(false);
	btnRemove.setVisible(false);
	lblNote.setVisible(false);
	lblHeaderRemove.setVisible(false);
    }

    /**
     * Shows the fields for adding a hired when someone with full access is using the program
     */
    private void showHiredAddFields ()
    {
	tpSubMenuHired.setVisible(true);
	lblHeaderAdd.setVisible(true);
	paneAddHired.setVisible(true);
	tfAddMail.setVisible(true);
	lblAddFirstName.setVisible(true);
	tfAddFirstName.setVisible(true);
        lblAddLastName.setVisible(true);
        tfAddLastName.setVisible(true);
	lblAddTelephone.setVisible(true);
	tfAddTelephone.setVisible(true);
	lblAddMail.setVisible(true);
	btnChangeHiredAdd.setVisible(true);
    }

    /**
     * Hides the fields for adding a hired when someone without full access is using the program
     */
    private void hideHiredAddFields ()
    {
	tpSubMenuHired.setVisible(false);
	lblHeaderAdd.setVisible(false);
	paneAddHired.setVisible(false);
	tfAddMail.setVisible(false);
	lblAddFirstName.setVisible(false);
	tfAddFirstName.setVisible(false);
        lblAddLastName.setVisible(false);
        tfAddLastName.setVisible(false);
	lblAddTelephone.setVisible(false);
	tfAddTelephone.setVisible(false);
	lblAddMail.setVisible(false);
	btnChangeHiredAdd.setVisible(false);
    }
    
    /**
     * Shows the fields for updating a Hired when someone with full access is using the program
     */
    private void showHiredUpdateFields ()
    {
	tpSubMenuHired.setVisible(true);
	paneUpdateHired.setVisible(true);
	lblChooseGameProject.setVisible(true);
	cbListAllGameProjects.setVisible(true);
	lblChooseProjectleader.setVisible(true);
	cbListAllProjectleaders.setVisible(true);
	btnConfirmUpdate.setVisible(true);
	lblUpdateLeader.setVisible(true);
        lblErrorMessagePlatform.setVisible(true);
    }

    /**
     * Hides the fields for updating a Hired when someone without full access is using the program
     */
    private void hideHiredUpdateFields ()
    {
	tpSubMenuHired.setVisible(false);
	paneUpdateHired.setVisible(false);
	lblChooseGameProject.setVisible(false);
	cbListAllGameProjects.setVisible(false);
	lblChooseProjectleader.setVisible(false);
	cbListAllProjectleaders.setVisible(false);
	btnConfirmUpdate.setVisible(false);
	lblUpdateLeader.setVisible(false);
        lblErrorMessagePlatform.setVisible(false);
    }

    /**
     * shows the fields for adding a gameproject when someone with full access is using the program
     */
    private void showGpAddFields ()
    {
	tpSubMenuGameProject.setVisible(true);
	paneAddGameProject.setVisible(true);
	lblHeaderAddGameProject.setVisible(true);
	lblInfoTextAddGameProject.setVisible(true);
	spGameProjectAdd.setVisible(false);
	tpReturnNewSID.setVisible(true);
	btnGenerateSID.setVisible(true);
	lblGpAddName.setVisible(true);
	tfGpAddName.setVisible(true);
	lblGpAddStartDate.setVisible(true);
	tfAddGpStartDate.setVisible(true);
	tfAddGpReleaseDate.setVisible(true);
	lblGpAddReleaseDate.setVisible(true);
	btnAddGameProject.setVisible(true);
    }
    
    /**
     * Hides the fields for adding a gameproject when someone without full access is using the program
     */
    private void hideGpAddFields ()
    {
	tpSubMenuGameProject.setVisible(false);
	paneAddGameProject.setVisible(false);
	lblHeaderAddGameProject.setVisible(false);
	lblInfoTextAddGameProject.setVisible(false);
	spGameProjectAdd.setVisible(true);
	tpReturnNewSID.setVisible(false);
	btnGenerateSID.setVisible(false);
	lblGpAddName.setVisible(false);
	tfGpAddName.setVisible(false);
	lblGpAddStartDate.setVisible(false);
	tfAddGpStartDate.setVisible(false);
	tfAddGpReleaseDate.setVisible(false);
	lblGpAddReleaseDate.setVisible(false);
	btnAddGameProject.setVisible(false);
	}
    
    /**
     * Shows the fields for changing a Gameproject when someone with full access is using the program
     */
    private void showGpChangeFields()
    {
	paneChangeGameProject.setVisible(true);
	lblHeaderChangeGameProject.setVisible(true);
	lblChooseGame.setVisible(true);
	cbListAllGames.setVisible(true);
	btnChooseChangeGameProject.setVisible(true);
	btnChangeGameProject.setVisible(true);
	tfChangeGpReleaseDate.setVisible(true);
	lblGpChangeReleaseDate.setVisible(true);
	lblGpChangeStartDate.setVisible(true);
	tfChangeGpStartDate.setVisible(true);
	tfGpChangeName.setVisible(true);
	lblGpChangeName.setVisible(true);
    }

    /**
     * Hides the fields for changing a gameproject when someone without full access is using the program
     */
    private void hideGpChangeFields()
    {
	paneChangeGameProject.setVisible(true);
	lblHeaderChangeGameProject.setVisible(true);
	lblChooseGame.setVisible(true);
	cbListAllGames.setVisible(true);
	btnChooseChangeGameProject.setVisible(true);
	btnChangeGameProject.setVisible(true);
	tfChangeGpReleaseDate.setVisible(true);
	lblGpChangeReleaseDate.setVisible(true);
	lblGpChangeStartDate.setVisible(true);
	tfChangeGpStartDate.setVisible(true);
	tfGpChangeName.setVisible(true);
	lblGpChangeName.setVisible(true);
    }
    
    /**
     * Sets the errormessage
     * @param text 
     */
    public void setErrorMessage(String text)
    {
        lblErrorMessageGameProject.setText(text);
    }
    
    /**
     * Gets the searchword
     * @return 
     */
    public String getSearchWord()
    {
        return tfsearchField.getText();
    }
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGameProject;
    private javax.swing.JButton btnChangeGameProject;
    private javax.swing.JButton btnChangeHired;
    private javax.swing.JButton btnChangeHiredAdd;
    private javax.swing.JButton btnChooseChangeGameProject;
    private javax.swing.JButton btnChooseChangeHired;
    private javax.swing.JButton btnConfirmUpdate;
    private javax.swing.JButton btnConfirmUpdateHired;
    private javax.swing.JButton btnConfirmUpdatePosition;
    private javax.swing.JButton btnConfirmUpdateRemoved;
    private javax.swing.JButton btnGenerateSID;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchCompetence;
    private javax.swing.JButton btnSearchGameProject;
    private javax.swing.JButton btnSearchPlatform;
    private javax.swing.JComboBox<String> cbFunctions;
    private javax.swing.JComboBox<String> cbFunctionsCompetence;
    private javax.swing.JComboBox<String> cbFunctionsGameProject;
    private javax.swing.JComboBox<String> cbFunctionsPlatform;
    private javax.swing.JComboBox<String> cbHiredForm;
    private javax.swing.JComboBox<String> cbListAllGameProjects;
    private javax.swing.JComboBox<String> cbListAllGameProjectsUpdate;
    private javax.swing.JComboBox<String> cbListAllGames;
    private javax.swing.JComboBox<String> cbListAllHired;
    private javax.swing.JComboBox<String> cbListAllHiredPosition;
    private javax.swing.JComboBox<String> cbListAllHiredRemove;
    private javax.swing.JComboBox<String> cbListAllProjectleaders;
    private javax.swing.JComboBox<String> cbListAllSpecialists;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAddFirstName;
    private javax.swing.JLabel lblAddLastName;
    private javax.swing.JLabel lblAddMail;
    private javax.swing.JLabel lblAddTelephone;
    private javax.swing.JLabel lblChangeMailHired;
    private javax.swing.JLabel lblChangeNameHired;
    private javax.swing.JLabel lblChangeTelephoneHired;
    private javax.swing.JLabel lblChooseGame;
    private javax.swing.JLabel lblChooseGameProject;
    private javax.swing.JLabel lblChooseGameProjectUpdate;
    private javax.swing.JLabel lblChooseHired;
    private javax.swing.JLabel lblChooseHiredPosition;
    private javax.swing.JLabel lblChooseHiredRemove;
    private javax.swing.JLabel lblChooseProjectleader;
    private javax.swing.JLabel lblChooseSpecialist;
    private javax.swing.JLabel lblChooseUpgrade;
    private javax.swing.JLabel lblErrorMessageCompetence;
    private javax.swing.JLabel lblErrorMessageGameProject;
    private javax.swing.JLabel lblErrorMessageHired;
    private javax.swing.JLabel lblErrorMessagePlatform;
    private javax.swing.JLabel lblFunctionError;
    private javax.swing.JLabel lblGpAddName;
    private javax.swing.JLabel lblGpAddReleaseDate;
    private javax.swing.JLabel lblGpAddStartDate;
    private javax.swing.JLabel lblGpChangeName;
    private javax.swing.JLabel lblGpChangeReleaseDate;
    private javax.swing.JLabel lblGpChangeStartDate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeaderAdd;
    private javax.swing.JLabel lblHeaderAddGameProject;
    private javax.swing.JLabel lblHeaderChangeGameProject;
    private javax.swing.JLabel lblHeaderChangeHired;
    private javax.swing.JLabel lblHeaderCompetence;
    private javax.swing.JLabel lblHeaderGameProject;
    private javax.swing.JLabel lblHeaderPlatform;
    private javax.swing.JLabel lblHeaderRemove;
    private javax.swing.JLabel lblInfoTextAddGameProject;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblUpdateHiredInProject;
    private javax.swing.JLabel lblUpdateHiredPosition;
    private javax.swing.JLabel lblUpdateLeader;
    private javax.swing.JPanel paneAddGameProject;
    private javax.swing.JPanel paneAddHired;
    private javax.swing.JPanel paneChangeGameProject;
    private javax.swing.JPanel paneChangeHired;
    private javax.swing.JPanel paneCompetence;
    private javax.swing.JPanel paneHired;
    private javax.swing.JPanel panePlatform;
    private javax.swing.JPanel paneProject;
    private javax.swing.JPanel paneRemoveHired;
    private javax.swing.JPanel paneUpdateHired;
    private javax.swing.JSeparator separatorGameProject;
    private javax.swing.JSeparator separatorHired;
    private javax.swing.JScrollPane spCompetence;
    private javax.swing.JScrollPane spGameProject;
    private javax.swing.JScrollPane spGameProjectAdd;
    private javax.swing.JScrollPane spHired;
    private javax.swing.JScrollPane spPlatform;
    private javax.swing.JTextArea tasearchResult;
    private javax.swing.JTextArea tasearchResultCompetence;
    private javax.swing.JTextArea tasearchResultGameProject;
    private javax.swing.JTextArea tasearchResultPlatform;
    private javax.swing.JTextField tfAddFirstName;
    private javax.swing.JTextField tfAddGpReleaseDate;
    private javax.swing.JTextField tfAddGpStartDate;
    private javax.swing.JTextField tfAddLastName;
    private javax.swing.JTextField tfAddMail;
    private javax.swing.JTextField tfAddTelephone;
    private javax.swing.JTextField tfChangeGpReleaseDate;
    private javax.swing.JTextField tfChangeGpStartDate;
    private javax.swing.JTextField tfChangeMailHired;
    private javax.swing.JTextField tfChangeNameHired;
    private javax.swing.JTextField tfChangeTelephoneHired;
    private javax.swing.JTextField tfGpAddName;
    private javax.swing.JTextField tfGpChangeName;
    private javax.swing.JTextField tfsearchField;
    private javax.swing.JTextField tfsearchFieldCompetence;
    private javax.swing.JTextField tfsearchFieldGameProject;
    private javax.swing.JTextField tfsearchFieldPlatform;
    private javax.swing.JTabbedPane tpMenu;
    private javax.swing.JTextPane tpReturnNewSID;
    private javax.swing.JTabbedPane tpSubMenuGameProject;
    private javax.swing.JTabbedPane tpSubMenuHired;
    // End of variables declaration//GEN-END:variables
}
